FROM python:3.9-slim

RUN mkdir -p /app

WORKDIR /app

COPY requirements.txt /app
RUN python3 -m pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

COPY . /app

# Copy the shell script into the image
COPY entrypoint.sh /app/entrypoint.sh
RUN chmod +x /app/entrypoint.sh

EXPOSE 8000
ENV PYTHONUNBUFFERED=1

# Set the entrypoint to your shell script
ENTRYPOINT ["/app/entrypoint.sh"]
# Keep your original CMD
CMD ["gunicorn", "transcendence.wsgi:application", "--bind", "0.0.0.0:8000", "--log-level", "debug", "--access-logfile", "-", "--error-logfile", "-"]
