# Generated by Django 4.2.16 on 2024-10-19 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pong', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='winner_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='user2',
            field=models.CharField(max_length=255),
        ),
    ]
