# Generated by Django 4.2.16 on 2024-10-19 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pong', '0002_match_winner_name_alter_match_user2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameplayhistory',
            name='date',
        ),
        migrations.AddField(
            model_name='match',
            name='match_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
